### ISSUE TITLE
simplify internal layout of `Model`

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui-old#11]
- ~~merge `beam` into `sequence`~~ [a4416ce]
- ~~merge `variables` into `sequence`~~ [1861e46]
- ~~unify access to `sequence` and `twiss`~~ [WONTFIX]
- ~~possibly derive from `cpymad.model` or expose all relevant methods otherwise~~ [WONTFIX]
- separate and rename components:
  - ~~matching~~ [4d7051d]
  - sequence access

**Comment by coldfix** [comment]
with the capability to [inspect sequences from memory](https://github.com/pymad/pymad/issues/38) it should be possible to drop the `sequence` member or at least create it dynamically.

**Comment by Eothred** [comment]
Not sure if I understand this one. You propose to change the structure of the json/yaml documents? Or the python class?

Edit: Haha, I clicked here through a link on the pymad issues list. Thought you were still talking about pymad :)

Sorry for the noise
